GO_EASY_ON_ME = 1

include theos/makefiles/common.mk

BUNDLE_NAME = Cleaner
Cleaner_FILES = Cleaner.mm
Cleaner_INSTALL_PATH = /System/Library/PreferenceBundles
Cleaner_FRAMEWORKS = UIKit
Cleaner_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
