GO_EASY_ON_ME = 1

include theos/makefiles/common.mk

BUNDLE_NAME = iCloud
iCloud_FILES = iCloud.mm
iCloud_INSTALL_PATH = /Library/PreferenceBundles
iCloud_FRAMEWORKS = UIKit
iCloud_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
