GO_EASY_ON_ME = 1

include theos/makefiles/common.mk

BUNDLE_NAME = SoftwareUpdate
SoftwareUpdate_FILES = SoftwareUpdate.mm
SoftwareUpdate_INSTALL_PATH = /Library/PreferenceBundles
SoftwareUpdate_FRAMEWORKS = UIKit
SoftwareUpdate_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk

